name = "platoscan-api"
main = "worker.js"
compatibility_date = "2026-01-01"

[[kv_namespaces]]
binding = "SCANS"
id = "a371c494efde42788c1bb75f9b30a7ca"

[vars]
ALLOWED_ORIGIN = "https://konfiozinc.github.io"
MODELS = "gemini-flash-latest,gemini-2.0-flash"   # cadena corta y rapida
